### ISSUE TITLE
视频播放循环中有bug

### ISSUE THREAD

**Issue by Dominic23331** [HW140701/RTMPose-Deploy#1]
`imshow("RTMPose", frame);
cv::waitKey(1);`
这里无法跳出循环

**Comment by HW140701** [comment]
您好，感谢您的反馈。
这里是有一点小问题，但是问题应该不是很大的，可能 就是交互体验不好，不影响核心功能，多按几次按键就好，我这就修改下代码。

**Comment by HW140701** [comment]
> `imshow("RTMPose", frame); cv::waitKey(1);` 这里无法跳出循环

已更新代码，可以重新拉取
