### ISSUE TITLE
直接运行时onnxruntime报错

### ISSUE THREAD

**Issue by huangzhenjie** [HW140701/RTMPose-Deploy#2]
错误信息：Non-zero status code returned while running Concat node. Name:'Concat_240' Status Message: concat.cc:157 onnxruntime::ConcatBase::PrepareForCompute Non concat axis dimensions must match: Axis 2 has mismatched dimensions of 135 and 136，这大概什么原因吗

**Comment by HW140701** [comment]
运行本项目报的错吗？

**Comment by huangzhenjie** [comment]
对，刚找到原因了，就是长和宽大小要一致才能正常运行

**Comment by huangzhenjie** [comment]
项目默认的输入是摄像头，我加载了自己的视频文件
