### ISSUE TITLE
大佬请教一下，这个是什么问题

### ISSUE THREAD

**Issue by XH-B** [HW140701/RTMPose-Deploy#3]
Windows/OnnxRumtime-CPU/src/RTMPoseOnnxRuntime/main.cpp:3:10: fatal error: "opencv2/opencv.hpp" file not found

**Comment by HW140701** [comment]
我这项目中在third目录下上传了opencv库，如果是visual studio打开项目文件，直接打开编译，不会出现找不到opencv头文件错的。
不知道你这个为什么会出现这个错误
