### ISSUE TITLE
直接运行失败

### ISSUE THREAD

**Issue by Luyuqing0920** [HW140701/RTMPose-Deploy#4]
大佬，请问我直接在Visual Studio中运行，显示应用程序无法正常启动0xc00007b，可能是什么问题？

**Comment by HW140701** [comment]
debug模式用ctrl+F5运行，如果不行试一下release是否正常吧

**Comment by Luyuqing0920** [comment]
已经解决，谢谢！请问您有在使用本地视频时会不会出现比摄像头卡顿的情况？

**Comment by HW140701** [comment]
我没有出现这种情况，如果你的本地视频帧率大于30可能会出现吧

**Comment by Luyuqing0920** [comment]
好的，感谢解答
